name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'

    - name: Build binaries
      run: |
        TAG=${GITHUB_REF##*/}
        mkdir -p dist
        
        # Linux AMD64
        GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o dist/kubenest-${TAG}-linux-amd64 ./cmd/kubenest
        
        # Linux ARM64
        GOOS=linux GOARCH=arm64 go build -ldflags="-s -w" -o dist/kubenest-${TAG}-linux-arm64 ./cmd/kubenest
        
        # macOS AMD64 (Intel)
        GOOS=darwin GOARCH=amd64 go build -ldflags="-s -w" -o dist/kubenest-${TAG}-darwin-amd64 ./cmd/kubenest
        
        # macOS ARM64 (Apple Silicon)
        GOOS=darwin GOARCH=arm64 go build -ldflags="-s -w" -o dist/kubenest-${TAG}-darwin-arm64 ./cmd/kubenest
        
        # Windows AMD64
        GOOS=windows GOARCH=amd64 go build -ldflags="-s -w" -o dist/kubenest-${TAG}-windows-amd64.exe ./cmd/kubenest
        
        # Windows ARM64
        GOOS=windows GOARCH=arm64 go build -ldflags="-s -w" -o dist/kubenest-${TAG}-windows-arm64.exe ./cmd/kubenest

    - name: Create checksums
      run: |
        cd dist
        sha256sum * > checksums.txt

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          dist/*
        body: |
          ## Kubenest CLI ${{ github.ref_name }}

          Download the CLI for your platform:

          ### Linux
          - **AMD64**: [kubenest-${{ github.ref_name }}-linux-amd64](./kubenest-${{ github.ref_name }}-linux-amd64)
          - **ARM64**: [kubenest-${{ github.ref_name }}-linux-arm64](./kubenest-${{ github.ref_name }}-linux-arm64)

          ### macOS
          - **Intel (AMD64)**: [kubenest-${{ github.ref_name }}-darwin-amd64](./kubenest-${{ github.ref_name }}-darwin-amd64)
          - **Apple Silicon (ARM64)**: [kubenest-${{ github.ref_name }}-darwin-arm64](./kubenest-${{ github.ref_name }}-darwin-arm64)

          ### Windows
          - **AMD64**: [kubenest-${{ github.ref_name }}-windows-amd64.exe](./kubenest-${{ github.ref_name }}-windows-amd64.exe)
          - **ARM64**: [kubenest-${{ github.ref_name }}-windows-arm64.exe](./kubenest-${{ github.ref_name }}-windows-arm64.exe)

          ### Checksums
          - [checksums.txt](./checksums.txt) - SHA256 checksums for all binaries

          ### Installation

          #### Linux/macOS
          ```bash
          # Download the binary for your platform
          curl -L -o kubenest https://github.com/kubenesthq/cli/releases/download/${{ github.ref_name }}/kubenest-${{ github.ref_name }}-<platform>-<arch>
          
          # Make it executable
          chmod +x kubenest
          
          # Move to PATH
          sudo mv kubenest /usr/local/bin/
          ```

          #### Windows
          Download the `.exe` file for your architecture and add it to your PATH.

          ### Usage
          ```bash
          kubenest --help
          ```
